Cache generalization
configcat/kotlin-sdk pull request #12
Opened 2023-05-22 22:47 UTC by novalisdenahi

### Describe the purpose of your pull request

- Generalized cache use epoch second for fetch time based on local system time.

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2023-06-14 17:13 UTC, adams85 requested changes
https://github.com/configcat/kotlin-sdk/pull/12/files#diff-18ca244a0703cb0d74ea90e4a2f5f6c45539935ac43eec21c14306da53552472R31

According to [the spec](https://trello.com/c/KVrX0A1x), config file name must include the extension (i.e. `config_v5.json`). 

Also, please don't forget to adjust the implementation to the spec changes:
* update the cache payload format to `v2`
* write millisec timestamp into the cache payload
* add common test cases (see https://github.com/configcat/.net-sdk/blob/5b545d4e08d5346457ba6dfb76ab92b558a1478e/src/ConfigCat.Client.Tests/ConfigCacheTests.cs#L231-L248)

2023-06-14 17:13 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/DateTimeUtils.kt
> +            val fetchTimeSeconds = fetchTime.toDouble()
According to the spec, we expect a 64-bit integer here so I suggest parsing it as an integer instead of a decimal value.

2023-06-20 08:59 UTC, adams85 requested changes
As [mentioned earlier](https://github.com/configcat/kotlin-sdk/pull/12#discussion_r1229924495), `DateTimeUtils.isValidDate` still seems out-of-sync.

2023-06-20 20:06 UTC, z4kn4fein approved these changes

2023-06-20 21:31 UTC, z4kn4fein requested changes
Please also check `detekt` code scanning warnings, and fix those that are valid.

2023-06-20 21:31 UTC, z4kn4fein commented on src/commonMain/kotlin/com/configcat/Config.kt
>                  throw IllegalArgumentException("Empty eTag value.")
Please use `require()` everywhere instead of directly throwing `IllegalArgumentException` as `detekt` suggests.

2023-06-20 21:31 UTC, z4kn4fein commented on src/commonMain/kotlin/com/configcat/DateTimeUtils.kt
> +            val fetchTimeSeconds = fetchTime.toDouble()
Please use `.toLongOrNull()` instead of swallowing the exception.

2023-06-21 15:56 UTC, z4kn4fein approved these changes

2023-06-21 15:58 UTC, adams85 approved these changes

2023-06-21 16:00 UTC, merged