Config v6
configcat/kotlin-sdk pull request #18
Opened 2023-10-24 20:14 UTC by novalisdenahi

### Describe the purpose of your pull request

Config v6 support:

- New SDK key format (validation)
- AND conditions
- Percentage options in targeting rules
- New condition types
  - Prerequisite Flag Condition
  - Segment Condition
- New comparison operators
- User Object attribute helper methods

Breaking changes:

- Rework `Config` and related ConfigCat models to support v6.
- Rename `EvaluationDetails` matchedEvaluationRule` to `matchedTargetingRule` and `matchedEvaluationPercentageRule` to `matchedPercentageOption`.

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2024-03-12 17:10 UTC, adams85 requested changes
Apart from the comments, I have some further tangential remarks:
1. As it turned out, the Kotlin SDK doesn't have a real end-to-end test (like a `getValue` call which pulls the config data from the CDN) as the HTTP communication is mocked in all the tests. That is, we can't really call e.g. the matrix tests integration tests currently. Obviously, this situation is not good and I think we should change it.
2. Another issue with the matrix tests and other data file-driven tests that the test data is not read from file but hardcoded in source files. This makes the review process harder and less efficient and also hurts maintainability. (For example, when we need to alter the test data in the future, a simple file copy won't be possible unlike in other SDKs.)
3. Exceptions used to control flow in the evaluation logic. (The same issue as the one discussed here: https://github.com/configcat/java-sdk/pull/39#discussion_r1439352583)

Based on our discussion with @novalisdenahi , solving these issues are not trivial and may take longer time. So I don't insist on solving them now, but I think we should take care of them sooner or later. As a matter of fact, I wouldn't mind if issue 1 were addressed now, but the decision is not up to me.

2024-03-20 21:08 UTC, novalisdenahi commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
>          }
We have to check again in the method, or we could use the ! operator, but we don't want that.

2024-03-20 21:19 UTC, novalisdenahi commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
>                  continue
Do you mean the error throw should be in the `getKeyAndValue`? The check is there `targetingRule.percentageOptions?` but we didn't throw error in the other SDKs as well. I don't think it's necessary.

2024-03-21 07:54 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
>          }
How about passing the array of targeting rules to the `evaluateTargetingRules` method as a non-nullable parameter? Something like this:

```kotlin
  private fun evaluateTargetingRules(
        targetingRules: Array<TargetingRule>,
        /*...*/
```

2024-03-21 08:08 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
>                  continue
As you can see, [the reference implementation does throw an error](https://github.com/configcat/.net-sdk/blob/985600c2f91c1b388187d09e50a0d3af40cf6bdc/src/ConfigCatClient/Evaluation/RolloutEvaluator.cs#L156), while the Kotlin SDK just continues evaluation (if I'm not missing here something).

As for `getKeyAndValue`, .NET SDK doesn't have this method currently, but others check this case:
* https://github.com/configcat/php-sdk/blob/master/src/ConfigCatClient.php#L546 (`hasPercentageOptions` throws when the THEN part is missing)
* https://github.com/configcat/cpp-sdk/blob/a6adaa0b56d7579448ac788fa83bc4c053d3380a/src/configcatclient.cpp#L317-L319
* https://github.com/configcat/swift-sdk/blob/c748d1bab8fc64f6b11cba9f131e5fbd789ed3b9/Sources/ConfigCat/ConfigCatClient.swift#L298-L300

If other SDKs don't do this check, that's an oversight and slipped past review unfortunately.

2024-03-21 09:08 UTC, novalisdenahi commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
> +                return Constants.json.decodeFromString(userAttribute)
It shouldn't allow null; the method returns with Array<String>, not with Array<String?>

2024-03-21 14:11 UTC, novalisdenahi commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
>                  continue
Yep, this should be fixed in Java, Android and Dart as well.

2024-03-22 11:57 UTC, adams85 requested changes

2024-03-22 11:57 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/model/SettingValue.kt
> +    public fun equalsBasedOnSettingType(other: Any?, settingType: Int): Boolean {
This method serves a special internal purpose, I'd rather not expose it to the end users.

```suggestion
    internal fun equalsBasedOnSettingType(other: Any?, settingType: Int): Boolean {
```

2024-03-22 11:57 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/model/SettingValue.kt
> +                doubleValue == other.doubleValue || integerValue == other.integerValue
Is it safe to assume that a value like `1` is always stored in `integerValue`, never in `doubleValue` (as `1.0`)?

How about something like this:

```suggestion
                (doubleValue ?? integerValue.toDouble()) == (other.doubleValue ?? other.integerValue.toDouble())
```

2024-03-22 11:57 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/Evaluator.kt
> +            return doubleToString(userValue.toString().toDouble())
I checked the reference implementation and it also does the "0.12345 is converted to something like 0.1234500120130" thing.

This is how float to double conversion works according to the IEEE 754 standard, so let's say that this is by design and remove the hack.

2024-03-22 14:24 UTC, adams85 commented on src/commonMain/kotlin/com/configcat/ConfigCatUser.kt
> + *  * all other values are automatically converted to string (a warning will be logged but evaluation will continue as normal).
```suggestion
 *  * all other values are automatically converted to `String` (a warning will be logged but evaluation will continue as normal).
```

2024-03-22 16:00 UTC, adams85 approved these changes

2024-03-25 10:19 UTC, z4kn4fein approved these changes
Please fix the reported detect warnings, but other than that 💚

2024-03-25 10:19 UTC, z4kn4fein commented on src/jsMain/kotlin/com/configcat/fetch/HttpRequestBuilder.kt
> +    val httpRequestBuilder = HttpRequestBuilder()
❤️

2024-04-02 10:25 UTC, merged